### ISSUE TITLE
dso-mgr rollout TODO

### ISSUE THREAD

**Issue by grst** [Boehringer-Ingelheim/dso-mgr#3]
### Description of feature

In https://github.com/Boehringer-Ingelheim/dso/issues/6, we introduced dso-mgr. 
Here are additional steps needed for fully rolling it out: 
- [ ] Rename binary of `dso-core` from `dso` into `dso-core` to avoid conflicts
- [x] pandocfilter https://github.com/Boehringer-Ingelheim/dso-mgr/issues/1
- [ ] Use dvc from virtual env
- [ ] Update installation instructions https://github.com/Boehringer-Ingelheim/dso/issues/56
- [ ] Add an env var for a global installation of dso (if the 'outside project' version shall not by dynamically installed via uv)
- [ ] Automatically check if dso within project is outdated

**Comment by grst** [comment]
Actually I could go with a single binary instead of dso-mgr:
 * all dependencies for main CLI optional
 * main CLI lazily imported
